In [1]:
import numpy as np
from astropy.stats import LombScargle
import csv
import scipy.io as sio
import matplotlib.pyplot as plt  

mat_contents = sio.loadmat('/home/aldo/Documents/Projects/Avtivemeter/Data/code_cruze_paper/Re actimetry/data_acti_4days.mat')

t = mat_contents['tt_4']
y = mat_contents['yy_4']

t = t.flatten()
y = y.flatten()
dy = 0.1

ls = LombScargle(t, y, dy)
freq, power = ls.autopower()
print(power.max()) 
print(ls.false_alarm_probability(power.max()))



0.122757671941
nan


/home/aldo/anaconda2/envs/Periodogram/lib/python3.5/site-packages/astropy/stats/lombscargle/_statistics.py:246: RuntimeWarning: invalid value encountered in sqrt
  Teff = np.sqrt(4 * np.pi * Dt)  # Effective baseline


In [2]:
import numpy as np
sio.savemat('/home/aldo/Documents/Projects/Avtivemeter/Data/code_cruze_paper/Re actimetry/freq.mat', {'freq':freq})
sio.savemat('/home/aldo/Documents/Projects/Avtivemeter/Data/code_cruze_paper/Re actimetry/power.mat', {'power':power})

In [3]:
best_frequency = freq[np.argmax(power)]
print("best frequency")
print(best_frequency)

best frequency
1.99925334259


In [4]:
1/best_frequency

0.5001867340646361

In [5]:
dy = 0.1
ls  = LombScargle(t,y,dy)

In [6]:
t_freq = 1/freq
indx = (t_freq > 1000).nonzero()
print(indx)
print(power[indx])

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28]),)
[ 0.03074096  0.03030061  0.02927569  0.02718089  0.02271362  0.01422595
  0.00523523  0.00203228  0.00167405  0.00059131  0.00044114  0.00363079
  0.01032918  0.01590968  0.01394629  0.00764018  0.00517956  0.01671007
  0.04895224  0.08855857  0.11710854  0.12156914  0.09317713  0.04862272
  0.01642984  0.00766594  0.01586478  0.02331834  0.01794906]


In [7]:
t_freq.compress((t_freq > 1000).flat)

array([ 57590.        ,  19196.66666667,  11518.        ,   8227.14285714,
         6398.88888889,   5235.45454545,   4430.        ,   3839.33333333,
         3387.64705882,   3031.05263158,   2742.38095238,   2503.91304348,
         2303.6       ,   2132.96296296,   1985.86206897,   1857.74193548,
         1745.15151515,   1645.42857143,   1556.48648649,   1476.66666667,
         1404.63414634,   1339.30232558,   1279.77777778,   1225.31914894,
         1175.30612245,   1129.21568627,   1086.60377358,   1047.09090909,
         1010.35087719])

In [8]:
times = t_freq[np.logical_and(t_freq>=1000, t_freq<=1800)]
print(times)
powers = power[np.logical_and(t_freq>=1000, t_freq<=1800)]
print(powers)

[ 1745.15151515  1645.42857143  1556.48648649  1476.66666667  1404.63414634
  1339.30232558  1279.77777778  1225.31914894  1175.30612245  1129.21568627
  1086.60377358  1047.09090909  1010.35087719]
[ 0.00517956  0.01671007  0.04895224  0.08855857  0.11710854  0.12156914
  0.09317713  0.04862272  0.01642984  0.00766594  0.01586478  0.02331834
  0.01794906]


In [13]:
from scipy.signal import find_peaks
yyy = find_peaks(powers)
print(yyy[0])
print(times[yyy[0]])   

[ 5 11]
[ 1339.30232558  1047.09090909]


In [9]:
from scipy.signal import find_peaks
yy = find_peaks(power[indx])
print(yy[0])
print(t_freq[yy[0]])   

[13 21 27]
[ 2132.96296296  1339.30232558  1047.09090909]


In [10]:
power_circ = 0.1216
ls.false_alarm_probability(power_circ)

/home/aldo/anaconda2/envs/Periodogram/lib/python3.5/site-packages/astropy/stats/lombscargle/_statistics.py:246: RuntimeWarning: invalid value encountered in sqrt
  Teff = np.sqrt(4 * np.pi * Dt)  # Effective baseline


nan

In [ ]:
ls.false_alarm_probability(power_circ, method='bootstrap')


In [ ]:
ls.false_alarm_probability(power_circ, method='davies')

In [11]:
ls.false_alarm_probability(power_circ, method='naive')  

1.1932435148134698e-158